import type { ImageModel } from "../types";

export async function generateImageBuffer(params: {
  prompt: string;
  referenceImages: string[];
  aspectRatio: string;
  imageSize: string;
  model: ImageModel;
}): Promise<{ buffer: Buffer; mimeType: string }> {
  const lingkeApiBaseUrl = process.env.LINGKE_API_BASE_URL ?? "https://lingkeapi.com";
  const lingkeApiKey = process.env.LINGKE_API_KEY ?? process.env.GEMINI_API_KEY;
  const lingkeBearerToken = process.env.LINGKE_BEARER_TOKEN ?? lingkeApiKey;

  if (!lingkeApiKey) {
    throw new Error("Missing LINGKE_API_KEY");
  }

  const parts: Array<Record<string, unknown>> = [];

  for (const img of params.referenceImages) {
    const [header, data] = img.split(",");
    if (!header || !data || !header.startsWith("data:")) {
      continue;
    }
    const mimeType = header.split(";")[0].replace("data:", "");
    parts.push({
      inline_data: {
        data,
        mime_type: mimeType,
      },
    });
  }

  const trimmedPrompt = params.prompt.trim();
  const finalPrompt = trimmedPrompt
    ? trimmedPrompt
    : params.referenceImages.length > 0
      ? "Generate an image based on the provided reference images."
      : "Generate a high quality image.";
  parts.push({ text: finalPrompt });

  const requestBody = {
    contents: [
      {
        role: "user",
        parts,
      },
    ],
    generationConfig: {
      responseModalities: ["TEXT", "IMAGE"],
      imageConfig: {
        aspectRatio: params.aspectRatio,
        imageSize: params.imageSize,
      },
    },
  };

  const headers: Record<string, string> = {
    "Content-Type": "application/json",
  };
  if (lingkeBearerToken) {
    headers.Authorization = `Bearer ${lingkeBearerToken}`;
  }

  const modelName =
    params.model === "v2"
      ? "gemini-3.1-flash-image-preview"
      : "gemini-3-pro-image-preview";

  const endpoint = `${lingkeApiBaseUrl.replace(/\/$/, "")}/v1beta/models/${modelName}:generateContent?key=${encodeURIComponent(lingkeApiKey)}`;
  const response = await fetch(endpoint, {
    method: "POST",
    headers,
    body: JSON.stringify(requestBody),
  });

  if (!response.ok) {
    const detail = await response.text();
    throw new Error(`Lingke image generation failed (${response.status}): ${detail.slice(0, 400)}`);
  }

  const payload = (await response.json()) as {
    candidates?: Array<{
      content?: {
        parts?: Array<{
          inlineData?: { data?: string; mimeType?: string };
          inline_data?: { data?: string; mime_type?: string };
        }>;
      };
    }>;
  };

  for (const part of payload.candidates?.[0]?.content?.parts || []) {
    const base64 = part.inlineData?.data ?? part.inline_data?.data;
    const mimeType = part.inlineData?.mimeType ?? part.inline_data?.mime_type;
    if (base64 && mimeType) {
      return {
        buffer: Buffer.from(base64, "base64"),
        mimeType,
      };
    }
  }

  throw new Error("No image generated by model");
}
